let score="33";
let score1="33abc";
console.log(typeof score);
let valueInnumber=Number(score);
console.log(valueInnumber);
console.log(typeof valueInnumber);
console.log(typeof score1);
let numberScore=Number(score1);
console.log(numberScore);//nan
console.log(typeof numberScore);
let start=true;
let num=Number(start);
console.log(typeof start);
console.log(start);
let score=undefined;
Number(score);
console.log(num);
let score="aa";
let num=Boolean(score);
console.log(num);